### PR TITLE
Fix for 2 vulnerable dependency paths

### PR DESCRIPTION
**Pull request by snyk-community**
hippie currently has a 4 vulnerable dependency paths, introducing 4 different types of known vulnerabilities.

This PR fixes vulnerable dependencies, [remote memory exposure ](https://snyk.io/vuln/npm:request:20160119) vulnerability in the `request` dependency, [ReDos vulnerability](https://snyk.io/vuln/npm:hawk:20160119) in the `hawk` dependency.

You can see [Snyk test report](https://snyk.io/test/github/vesln/hippie) of this project for details. 

This PR changes `Package.json` to upgrade `request` to the newer 2.74.0 version, and will fix the vulnerability listed above.
You can get alerts and fix PRs for future vulnerabilities for free by [watching this repo with Snyk](https://snyk.io/add).

Note this PR fixes all the vulnerabilities introduced trough `request` dependency, in order to be vulnerability free you will need to upgrade `qs` dependency as well.

Stay Secure,
The Snyk Team

### CODE REVIEW

**Comment by wilmoore** [comment]
@vesln and @CacheControl - do you see any reason we should not to pull this in ASAP?

**Comment by vesln** [comment]
i had this wedding thing going on during the past couple of weeks, so i must catch up with stuff. please free free to merge and ship it in case looks good to you

**Comment by wilmoore** [comment]
@vesln - congrats man...I didn't know you were getting married!

As for the PR; I'm happy to merge and ship if you want to give me permissions to do so.

**Comment by CacheControl** [comment]
LGTM; merging and deploying as `0.5.1`

**Comment by CacheControl** [comment]
Also congrats @vesln on the "wedding thing"!

**Comment by wilmoore** [comment]
👍

**Pull request merged**
